FROM ubuntu:18.04
COPY init_client.py /home
WORKDIR /home
RUN apt-get update
RUN apt-get install -y python-pip
EXPOSE 18810
EXPOSE 18811
EXPOSE 18812
EXPOSE 18813
EXPOSE 18814
EXPOSE 18815
EXPOSE 18816
EXPOSE 18817
EXPOSE 18818
EXPOSE 18819
EXPOSE 18820
# CMD ["python", "init_client.py", "localhost", "15089", "os,numpy,sys,timeit,pandas,sklearn.ensemble,sklearn.preprocessing,sklearn.metrics", "3000", "8", "100"]