FROM ubuntu:18.04

RUN apt-get update

RUN apt-get install -y python-pip libsm6 libxext6 libxrender1

RUN pip install --upgrade pip
RUN pip install \
	tensorflow==2.1 \
	keras==2.3.1 \
	rpyc \
	pandas \
  opencv-python==4.2.0.32

RUN apt-get clean
