FROM ubuntu:18.04

RUN apt-get update

RUN apt-get install -y python-pip

RUN pip install --upgrade pip
RUN pip install \
	tensorflow==2.1 \
	keras==2.3.1 \
	rpyc \
	pandas 

RUN apt-get clean

EXPOSE 15088
EXPOSE 15089
