version: "3.8"
networks:
  sid:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  module:
    build:
      context: .
      dockerfile: Dockerfile.server.tensorflow
    ports:
      - "15088:15088"
      - "15089:15089"
    volumes:
      - ./server:/mlfv
    container_name: 'mlfv-module'
    networks:
      sid:
        ipv4_address: 172.20.0.8
    working_dir: '/mlfv'
    command: ["python", "MLFV_Module.py"]
  client-cpu:
    image: mlfv-30_client-cpu:latest
    build:
      context: .
      dockerfile: Dockerfile.client.tensorflow
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3G
    volumes:
      - ./client:/mlfv
    networks:
      sid:
        ipv4_address: 172.20.0.9
    working_dir: '/mlfv'
    container_name: 'client-cpu_1'
    command: ["python", "init_client.py", "172.20.0.8", "15089", "numpy,pandas,tensorflow", "os,sys,timeit,numpy,pandas,tensorflow", "3000000000", "2", "100"]
    depends_on:
      - module
  client-gpu:
    image: mlfv-30_client-gpu:latest
    build:
      context: .
      dockerfile: Dockerfile.client.tensorflow
    deploy:
      resources:
        reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
        limits:
          cpus: '2'
          memory: 3G
    volumes:
      - ./client:/mlfv
    networks:
      sid:
        ipv4_address: 172.20.0.10
    working_dir: '/mlfv'
    container_name: 'client-gpu_1'
    command: ["python", "init_client.py", "172.20.0.8", "15089", "numpy,pandas,tensorflow", "os,sys,timeit,numpy,pandas,tensorflow", "3000000000", "2", "100", "0"]
    depends_on:
      - module
  client-test:
    image: mlfv-30_client-test:latest
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./test:/mlfv
    networks:
      sid:
        ipv4_address: 172.20.0.11
    working_dir: '/mlfv'
    container_name: 'client-test'
    command: ["python", "test_lenet.py"]
    depends_on:
      - client-cpu
